---
version: "3.8"

networks:
  frontend0:
    name: frontend0
  dmz:

volumes:
  traefik_certs:

services:
  traefik:
    image: library/traefik:v2.3
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=frontend0"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web-alt.address=:8080"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    restart: always
    networks:
      frontend0:
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - traefik_certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN}`) && (PathPrefix(`/api`) || PathPrefix
      (`/dashboard`))"
      - "traefik.http.routers.dashboard.entrypoints=web-alt"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.middlewares.secHeaders.headers.accesscontrolallowcredentials=true"
      - "traefik.http.middlewares.secHeaders.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.secHeaders.headers.accesscontrolallowmethods=post,options"
      - "traefik.http.middlewares.secHeaders.headers.accesscontrolalloworiginlist=${DOMAIN}"
      - "traefik.http.middlewares.secHeaders.headers.accesscontrolalloworigin=${DOMAIN}"
      - "traefik.http.middlewares.secHeaders.headers.framedeny=true"
      - "traefik.http.middlewares.secHeaders.headers.sslredirect=true"
      - "traefik.http.middlewares.secHeaders.headers.browserxssfilter=true"
      - "traefik.http.middlewares.secHeaders.headers.contenttypenosniff=true"
      - "traefik.http.middlewares.secHeaders.headers.referrerpolicy=strict-origin"
      - "traefik.http.middlewares.secHeaders.headers.stspreload=true"
      - "traefik.http.middlewares.secHeaders.headers.stsincludesubdomains=true"
      - "traefik.http.middlewares.secHeaders.headers.customresponseheaders.X-Powered-By="
      - "traefik.http.middlewares.secHeaders.headers.customresponseheaders.X-DNS-Prefetch-Control=off"
      - "traefik.http.middlewares.secHeaders.headers.customresponseheaders.X-Permitted-Cross-Domain-Policies=none"

  host:
    build: qontakt-host
    networks:
      frontend0:
      dmz:
        aliases:
          - q-host-service
    environment:
      - DOMAIN
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.q-host.rule=Host(`${DOMAIN}`) && PathPrefix(`/api/v1/host`)"
      - "traefik.http.routers.q-host.entrypoints=websecure"
      - "traefik.http.routers.q-host.tls=true"
      - "traefik.http.routers.q-host.middlewares=secHeaders"

  user:
    build: qontakt-user
    networks:
      frontend0:
      dmz:
        aliases:
          - q-user-service
    environment:
      - DOMAIN
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.q-user.rule=Host(`${DOMAIN}`) && PathPrefix(`/api/v1/user`)"
      - "traefik.http.routers.q-user.entrypoints=websecure"
      - "traefik.http.routers.q-user.tls=true"
      - "traefik.http.routers.q-user.middlewares=secHeaders"