---
version: "3.8"

networks:
  preauth0:
    name: preauth0
  postauth0:
    name: postauth0
  kratos0:
    name: kratos0
  dmz0:
    name: dmz0

volumes:
  traefik_certs:
    name: traefik_certs
  mariadb_crypto_data:
    name: mariadb_crypto_data
  mariadb_host_data:
    name: mariadb_host_data
  mariadb_user_data:
    name: mariadb_user_data
  postgres_data:
    name: postgres_data

services:
  # TLS encryption and drop headers
  traefik_tls:
    build: traefik
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=preauth0"
      - "--providers.docker.constraints=Label(`qontakt`, `external`)"
      - "--providers.file=true"
      - "--providers.file.directory=/conf"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web-alt.address=:8080"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.le.acme.dnschallenge=true"
      - "--certificatesresolvers.le.acme.dnschallenge.resolvers=8.8.8.8:53"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=hetzner"
      - "--certificatesresolvers.le.acme.email=services@galaxion.de"
      - "--certificatesresolvers.le.acme.storage=/certs/acme.json"
    restart: always
    networks:
      preauth0:
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - traefik_certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - "HETZNER_API_KEY"
    labels:
      qontakt: external
      traefik.enable: "true"
      traefik.http.routers.dashboard.rule: Host(`traefik_ext.${DOMAIN}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      traefik.http.routers.dashboard.entrypoints: web-alt
      traefik.http.routers.dashboard.middlewares: secHeaders@file
      traefik.http.routers.dashboard.service: api@internal
      traefik.http.routers.dashboard.tls: "true"
      traefik.http.routers.dashboard.tls.certresolver: le
      traefik.http.routers.dashboard.tls.domains[0].main: ${DOMAIN}
      traefik.http.routers.dashboard.tls.domains[0].sans: "*.${DOMAIN}"

  # Auth
  oathkeeper:
    build: oathkeeper
    command: serve proxy -c "/etc/config/oathkeeper/config.yml"
    restart: always
    networks:
      preauth0:
      postauth0:
    depends_on:
      - kratos
    expose:
      - 4455
    environment:
      LOG_LEVEL: debug
    labels:
      qontakt: external
      traefik.enable: "true"
      traefik.http.routers.oathkeeper.rule: HostRegexp(`{host:.+}`)
      traefik.http.routers.oathkeeper.entrypoints: websecure
      traefik.http.routers.oathkeeper.tls: "true"
      traefik.http.routers.oathkeeper.middlewares: secHeaders@file

  kratos:
    build: kratos
    command: serve -c /etc/config/kratos/config.yml
    restart: always
    networks:
      postauth0:
      kratos0:
    expose:
      - 4433
    environment:
      SESSION_COOKIE_DOMAIN: ${DOMAIN}
      SECRETS_DEFAULT: ${KRATOS_SECRET}
      COURIER_SMTP_CONNECTION_URI: ${KRATOS_SMTP}
      SERVE_PUBLIC_BASE_URL: https://${DOMAIN}/.ory/kratos/public
      DSN: postgres://kratos:${KRATOS_POSTGRES_PWD}@postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4

  postgres:
    image: library/postgres:13.1-alpine
    restart: always
    networks:
      kratos0:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kratos
      POSTGRES_PASSWORD: ${KRATOS_POSTGRES_PWD}


  # Application Gateway
  traefik_int:
    image: library/traefik:v2.3
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=postauth0"
      - "--providers.docker.constraints=Label(`qontakt`, `internal`)"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-alt.address=:8081"
    restart: always
    networks:
      postauth0:
    expose:
      - 80
    ports:
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: "true"
      traefik.http.routers.dashboard-int.rule: Host(`traefik_int.${DOMAIN}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      traefik.http.routers.dashboard-int.entrypoints: web-alt
      traefik.http.routers.dashboard-int.service: api@internal
      traefik.http.routers.dashboard-int.tls: "true"
      qontakt: internal

  webui:
    build: qontakt-webui
    restart: always
    networks:
      postauth0:
    labels:
      traefik.enable: "true"
      traefik.http.routers.webui.rule: PathPrefix(`/`)  # All other requests
      traefik.http.routers.webui.entrypoints: web

  crypto:
    build: qontakt-crypto
    networks:
      postauth0:
      dmz0:
        aliases:
          - q-crypto-service
    environment:
      MARIADB_PASSWORD: ${QONTAKT_MARIADB_PWD}
      spring_profiles_active: prod
    labels:
      traefik.enable: "true"
      traefik.http.routers.q-crypto.rule: PathPrefix(`/api/v1/crypto`)
      traefik.http.routers.q-crypto.entrypoints: web

  mariadb_crypto:
    image: library/mariadb:10.5
    restart: always
    networks:
      dmz0:
    volumes:
      - mariadb_crypto_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: qcrypto
      MYSQL_USER: qontakt
      MYSQL_PASSWORD: ${QONTAKT_MARIADB_PWD}
      MYSQL_RANDOM_ROOT_PASSWORD: 1

  host:
    build: qontakt-host
    networks:
      postauth0:
      dmz0:
        aliases:
          - q-host-service
    environment:
      MARIADB_PASSWORD: ${QONTAKT_MARIADB_PWD}
      spring_profiles_active: prod
    labels:
      traefik.enable: "true"
      traefik.http.routers.q-host.rule: PathPrefix(`/api/v1/host`)
      traefik.http.routers.q-host.entrypoints: web

  mariadb_host:
    image: library/mariadb:10.5
    restart: always
    networks:
      dmz0:
    volumes:
      - mariadb_host_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: qhost
      MYSQL_USER: qontakt
      MYSQL_PASSWORD: ${QONTAKT_MARIADB_PWD}
      MYSQL_RANDOM_ROOT_PASSWORD: 1

  user:
    build: qontakt-user
    networks:
      postauth0:
      dmz0:
        aliases:
          - q-user-service
    environment:
      MARIADB_PASSWORD: ${QONTAKT_MARIADB_PWD}
      spring_profiles_active: prod
    labels:
      traefik.enable: "true"
      traefik.http.routers.q-user.rule: PathPrefix(`/api/v1/user`)
      traefik.http.routers.q-user.entrypoints: web

  mariadb_user:
    image: library/mariadb:10.5
    restart: always
    networks:
      dmz0:
    volumes:
      - mariadb_user_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: quser
      MYSQL_USER: qontakt
      MYSQL_PASSWORD: ${QONTAKT_MARIADB_PWD}
      MYSQL_RANDOM_ROOT_PASSWORD: 1